repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #  rev: v4.4.0  # use the latest stable version
  #  hooks:
  #    - id: end-of-file-fixer
  #    - id: trailing-whitespace
  #    - id: check-added-large-files

  - repo: local
    hooks:
      - id: pylint-check
        name: Run pylint
        entry: bash scripts/run_pylint.sh
        language: system
        types: [python]
        stages: [commit]
        always_run: true

      - id: coverage-check
        name: Check test coverage
        entry: bash scripts/run_coverage.sh
        language: system
        types: [python]
        stages: [push]
        always_run: true
